#!/usr/bin/env python3
"""Generate per-port `.github/workflows/build-debs.yml` workflows.

Reads repositories.yml and emits a CI workflow for each safelibs/port-*
repository checked out on disk. The generated workflow builds the port debs in
that port repository, then publishes the .deb artifacts to a per-commit GitHub
release. The apt repo consumes those releases when assembling the signed apt repo.

The workflow is gated to:
  * build on every push, pull_request, and workflow_dispatch
  * publish a `build-<12char-sha>` GitHub release with the .deb artifacts
    only on push events (PRs from forks do not have release privileges).
"""
from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path
from typing import Any

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
APT_REPO_ROOT = SCRIPT_DIR.parent
if str(APT_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(APT_REPO_ROOT))

from tools.build_site import detect_rust_toolchain, safe_debian_script

DEFAULT_CONFIG = APT_REPO_ROOT / "repositories.yml"
DEFAULT_PORTS_ROOT = APT_REPO_ROOT.parent

GENERATED_HEADER = (
    "# AUTO-GENERATED by apt/tools/generate_port_ci.py. Do not edit by\n"
    "# hand - update repositories.yml or the generator and rerun\n"
    "# `make generate-port-ci` in the apt checkout.\n"
)

DEFAULT_BUILD: dict[str, Any] = {"mode": "safe-debian", "artifact_globs": ["*.deb"]}

SAFE_DEBIAN_EXTRA_PACKAGES = [
    "build-essential",
    "devscripts",
    "dpkg-dev",
    "equivs",
    "fakeroot",
]

# Manual overrides for ports not present in repositories.yml. The schema
# matches a repositories.yml `repositories[]` entry.
UNLISTED_PORT_OVERRIDES: dict[str, dict[str, Any]] = {
    "libjansson": {
        "build": {
            "mode": "docker",
            "workdir": ".",
            "packages": [
                "autoconf",
                "automake",
                "build-essential",
                "cargo",
                "dpkg-dev",
                "libtool",
                "pkg-config",
                "rustc",
            ],
            "command": (
                'bash safe/scripts/build-deb.sh\n'
                'mkdir -p "$SAFEAPTREPO_OUTPUT"\n'
                'cp -v safe/dist/*.deb "$SAFEAPTREPO_OUTPUT"/'
            ),
            "artifact_globs": ["*.deb"],
        },
    },
}


def dedupe(values: list[str]) -> list[str]:
    return list(dict.fromkeys(values))


def load_config(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text())
    if not isinstance(data, dict):
        raise SystemExit(f"{path}: expected a YAML mapping")
    return data


def port_dirs(ports_root: Path) -> list[Path]:
    return sorted(
        p for p in ports_root.iterdir()
        if p.is_dir() and p.name.startswith("port-") and (p / ".git").exists()
    )


def has_safelibs_remote(port_dir: Path) -> bool:
    git_config = port_dir / ".git" / "config"
    if not git_config.exists():
        return False
    return "safelibs/" in git_config.read_text()


def port_name(port_dir: Path) -> str:
    name = port_dir.name
    return name[len("port-"):] if name.startswith("port-") else name


def build_entry_for(
    config: dict[str, Any], name: str
) -> dict[str, Any]:
    """Return the apt repo repository entry for this port, falling back to
    manual overrides or the default safe-debian build if the port is not
    listed in repositories.yml."""
    for entry in config.get("port_build_overrides", []) or []:
        if str(entry.get("name")) == name:
            return entry
    override = UNLISTED_PORT_OVERRIDES.get(name)
    if override:
        return {"name": name, **override}
    return {"name": name, "build": dict(DEFAULT_BUILD)}


def rustup_setup_lines(toolchain: str) -> list[str]:
    return [
        (
            "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs "
            f"| sh -s -- -y --profile minimal --default-toolchain {shlex.quote(toolchain)}"
        ),
        'source "$HOME/.cargo/env"',
        "rustc --version",
        "cargo --version",
    ]


def resolve_build(
    entry: dict[str, Any], archive: dict[str, Any], port_dir: Path | None = None
) -> tuple[str, str, list[str], list[str], str, str]:
    """Return (mode, workdir, packages, setup_steps, rustup_toolchain, inner_script)."""
    build = dict(entry.get("build") or DEFAULT_BUILD)
    mode = str(build.get("mode") or "docker")
    packages = dedupe(
        list(archive.get("install_packages") or [])
        + list(build.get("packages") or [])
    )
    rustup_toolchain = str(build.get("rustup_toolchain") or "").strip()
    setup_script = str(build.get("setup") or "").strip()

    if mode == "checkout-artifacts":
        workdir = str(build.get("workdir") or ".")
        inner_script = (
            'mkdir -p "$SAFEAPTREPO_OUTPUT"\n'
            'cp -v *.deb "$SAFEAPTREPO_OUTPUT"/'
        )
        return mode, workdir, packages, [], rustup_toolchain, inner_script

    if mode == "safe-debian":
        default_workdir = "safe"
        workdir = str(build.get("workdir") or default_workdir)
        packages = dedupe(packages + SAFE_DEBIAN_EXTRA_PACKAGES)
        if not rustup_toolchain and port_dir is not None:
            # Same heuristic build_site.py uses: detect Cargo.lock v4 and
            # rust-version >= minimum-supported-by-ubuntu. Returns "" if the
            # system rustc is sufficient.
            detected = detect_rust_toolchain(port_dir / workdir)
            if detected:
                rustup_toolchain = detected
        inner_script = safe_debian_script()
    elif mode == "docker":
        default_workdir = "."
        workdir = str(build.get("workdir") or default_workdir)
        command = str(build.get("command") or "").strip()
        if not command:
            raise SystemExit(f"{entry.get('name')}: docker mode requires a command")
        inner_script = command
    else:
        raise SystemExit(f"{entry.get('name')}: unsupported build mode {mode!r}")

    if rustup_toolchain and "curl" not in packages:
        packages = dedupe(packages + ["curl"])

    setup_steps: list[str] = []
    if rustup_toolchain:
        setup_steps.extend(rustup_setup_lines(rustup_toolchain))
    if setup_script:
        setup_steps.append(setup_script)
    return mode, workdir, packages, setup_steps, rustup_toolchain, inner_script


def indent_block(text: str, indent: str) -> str:
    if not text:
        return ""
    return "\n".join(indent + line if line else "" for line in text.splitlines())


def render_container_script(
    workdir: str,
    packages: list[str],
    setup_steps: list[str],
    inner_script: str,
) -> str:
    """Render the bash script executed inside the docker container. This
    mirrors the script assembled by build_site.build_repo."""
    install_line = " \\\n  ".join(sorted(packages))
    lines: list[str] = [
        "set -euo pipefail",
        "trap 'chown -R \"${HOST_UID}:${HOST_GID}\" /workspace/source /workspace/output' EXIT",
        "export DEBIAN_FRONTEND=noninteractive",
        "apt-get update",
        "apt-get install -y --no-install-recommends \\\n  " + install_line,
    ]
    lines.extend(setup_steps)
    lines.extend(
        [
            "git config --global --add safe.directory /workspace/source",
            f"cd {shlex.quote(workdir)}",
            inner_script,
        ]
    )
    return "\n".join(lines)


def render_workflow(
    entry: dict[str, Any], archive: dict[str, Any], port_dir: Path | None = None
) -> str:
    _mode, workdir, packages, setup_steps, _toolchain, inner_script = resolve_build(
        entry, archive, port_dir
    )
    image = str(
        (entry.get("build") or {}).get("image")
        or archive.get("image")
        or "ubuntu:24.04"
    )
    container_script = render_container_script(
        workdir, packages, setup_steps, inner_script
    )
    container_script_block = indent_block(container_script, "          ")
    return f"""{GENERATED_HEADER}
name: build-debs

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      IMAGE: {image}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare output directory
        run: mkdir -p "$GITHUB_WORKSPACE/.ci/artifacts"

      - name: Write container build script
        run: |
          set -euo pipefail
          mkdir -p .ci
          cat >.ci/build.sh <<'SAFELIBS_PORT_CI_SCRIPT'
{container_script_block}
          SAFELIBS_PORT_CI_SCRIPT
          chmod +x .ci/build.sh

      - name: Build safe debs
        run: |
          set -euo pipefail
          docker run --rm \\
            --mount "type=bind,src=$GITHUB_WORKSPACE,dst=/workspace/source" \\
            --mount "type=bind,src=$GITHUB_WORKSPACE/.ci/artifacts,dst=/workspace/output" \\
            -w /workspace/source \\
            -e SAFEAPTREPO_SOURCE=/workspace/source \\
            -e SAFEAPTREPO_OUTPUT=/workspace/output \\
            -e SAFEDEBREPO_SOURCE=/workspace/source \\
            -e SAFEDEBREPO_OUTPUT=/workspace/output \\
            -e HOST_UID="$(id -u)" \\
            -e HOST_GID="$(id -g)" \\
            "$IMAGE" \\
            bash /workspace/source/.ci/build.sh

      - name: List built artifacts
        run: ls -la .ci/artifacts

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debs
          path: .ci/artifacts/*.deb
          if-no-files-found: error

      - name: Publish GitHub release
        if: github.event_name == 'push'
        env:
          GH_TOKEN: ${{{{ github.token }}}}
        run: |
          set -euo pipefail
          short_sha="${{GITHUB_SHA:0:12}}"
          tag="build-${{short_sha}}"
          title="Build ${{short_sha}}"
          notes="Automated safe-deb build of ${{GITHUB_SHA}} for $(date -u +%FT%TZ)."
          if gh release view "$tag" --repo "$GITHUB_REPOSITORY" >/dev/null 2>&1; then
            gh release upload "$tag" --repo "$GITHUB_REPOSITORY" --clobber .ci/artifacts/*.deb
          else
            gh release create "$tag" \\
              --repo "$GITHUB_REPOSITORY" \\
              --title "$title" \\
              --notes "$notes" \\
              --target "$GITHUB_SHA" \\
              .ci/artifacts/*.deb
          fi
"""


def write_workflow(port_dir: Path, content: str) -> tuple[bool, Path]:
    dest = port_dir / ".github" / "workflows" / "build-debs.yml"
    dest.parent.mkdir(parents=True, exist_ok=True)
    previous = dest.read_text() if dest.exists() else None
    if previous == content:
        return False, dest
    dest.write_text(content)
    return True, dest


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument(
        "--ports-root",
        type=Path,
        default=DEFAULT_PORTS_ROOT,
        help="directory containing the port-* checkouts (defaults to the apt repo's parent)",
    )
    parser.add_argument(
        "--skip",
        action="append",
        default=[],
        help="port directory names to skip (may be repeated)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print what would change without writing any files",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    config = load_config(args.config)
    archive = config.get("archive") or {}
    skips = set(args.skip)
    ports = [p for p in port_dirs(args.ports_root) if p.name not in skips]
    written = 0
    unchanged = 0
    missing_remote: list[str] = []
    for port_dir in ports:
        if not has_safelibs_remote(port_dir):
            missing_remote.append(port_dir.name)
            continue
        name = port_name(port_dir)
        entry = build_entry_for(config, name)
        try:
            content = render_workflow(entry, archive, port_dir)
        except SystemExit as exc:
            print(f"{port_dir.name}: {exc}", file=sys.stderr)
            return 2
        if args.dry_run:
            dest = port_dir / ".github" / "workflows" / "build-debs.yml"
            current = dest.read_text() if dest.exists() else None
            label = "would-update" if current != content else "up-to-date"
            print(f"{label}: {dest}")
            continue
        changed, dest = write_workflow(port_dir, content)
        if changed:
            written += 1
            print(f"wrote {dest}")
        else:
            unchanged += 1
    if missing_remote:
        print(
            f"skipped (no safelibs remote): {', '.join(missing_remote)}",
            file=sys.stderr,
        )
    if not args.dry_run:
        print(f"summary: {written} written, {unchanged} unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
